"""empty message

Revision ID: 94a582263e82
Revises: 9d76462513b2
Create Date: 2025-04-19 21:42:48.363483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a582263e82'
down_revision = '9d76462513b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Float(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
