"""empty message

Revision ID: bf6dcb3faf0b
Revises: c11a9a836db5
Create Date: 2025-04-19 19:48:25.014940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6dcb3faf0b'
down_revision = 'c11a9a836db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('time_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('time_seen',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
